[pytest]

testpaths = tests

addopts = -sv --alluredir=allure-results

markers = 
    positive: положительные тесты с верными данными
    negative: отрицательные тесты с неверными данными
    users: тесты /users
    products: тесты /products
    quotes: тесты /quotes
    comments: тесты /comments
    posts: тесты /posts
    recipes: тесты /recipes
    carts: тесты /carts